require('config.clipboard')
require('config.autocmd')
require('config.colors')
require('config.filetype')
require('config.globals')
require('config.options')
require('config.fold')
require('config.colorscheme')

require('config.plugins')
