local opt = vim.opt
opt.background = 'dark'
opt.backspace = '2'
opt.cmdheight = 2
opt.compatible = false
opt.cursorline = true
opt.encoding = 'utf-8'
opt.expandtab = true
opt.foldcolumn = '1' -- '0' is not bad
opt.foldenable = true
opt.foldlevel = 99   -- Using ufo provider need a large value, feel free to decrease the value
opt.foldlevelstart = 99
opt.foldmethod = 'indent'
opt.foldnestmax = 10
opt.hidden = true
opt.hlsearch = true
opt.incsearch = true
opt.laststatus = 2
opt.lazyredraw = true
opt.list = true
opt.listchars = 'eol:↲,trail:·,tab:»·,extends:»,precedes:«'
opt.modifiable = true
opt.number = true
opt.shiftwidth = 2
opt.showmatch = true
opt.signcolumn = 'yes'
opt.smartindent = true
opt.softtabstop = 4
opt.tabstop = 4
opt.termguicolors = true
opt.updatetime = 250
opt.wildmenu = true
opt.swapfile = false
opt.spell = false
