-- additional configuration required for plugins to work
require('config.plugins.bufferline')
require('config.plugins.cmp')
require('config.plugins.cmp-copilot')
require('config.plugins.cmp-git')
require('config.plugins.cmp-npm')
require('config.plugins.nvim-dap')
require('config.plugins.nvim-tree')
require('config.plugins.none-ls')
require('config.plugins.treesitter')
